//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidMassTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_UserController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_UserController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidMassTesting.Resources.Controllers.UserController", typeof(Controllers_UserController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty.
        /// </summary>
        internal static string Email_must_not_be_empty {
            get {
                return ResourceManager.GetString("Email must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Admin role can list users.
        /// </summary>
        internal static string Only_user_with_Admin_role_can_list_users {
            get {
                return ResourceManager.GetString("Only user with Admin role can list users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Registration Manager role can select his own place..
        /// </summary>
        internal static string Only_user_with_Registration_Manager_role_can_select_his_own_place_ {
            get {
                return ResourceManager.GetString("Only user with Registration Manager role can select his own place.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place must not be empty.
        /// </summary>
        internal static string Place_must_not_be_empty {
            get {
                return ResourceManager.GetString("Place must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This special user cannot change the password..
        /// </summary>
        internal static string This_special_user_cannot_change_the_password_ {
            get {
                return ResourceManager.GetString("This special user cannot change the password.", resourceCulture);
            }
        }
    }
}
