//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidMassTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_ResultController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_ResultController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidMassTesting.Resources.Controllers.ResultController", typeof(Controllers_ResultController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the test set must not be empty.
        /// </summary>
        internal static string Code_of_the_test_set_must_not_be_empty {
            get {
                return ResourceManager.GetString("Code of the test set must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid result state.
        /// </summary>
        internal static string Invalid_result_state {
            get {
                return ResourceManager.GetString("Invalid result state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid visitor code.
        /// </summary>
        internal static string Invalid_visitor_code {
            get {
                return ResourceManager.GetString("Invalid visitor code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 4 digits of personal number or declared passport for foreigner at registration must not be empty.
        /// </summary>
        internal static string Last_4_digits_of_personal_number_or_declared_passport_for_foreigner_at_registration_must_not_be_empty {
            get {
                return ResourceManager.GetString("Last 4 digits of personal number or declared passport for foreigner at registrati" +
                        "on must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Data Exporter role is allowed to fetch all sick visitors.
        /// </summary>
        internal static string Only_user_with_Data_Exporter_role_is_allowed_to_fetch_all_sick_visitors {
            get {
                return ResourceManager.GetString("Only user with Data Exporter role is allowed to fetch all sick visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Document Manager role is allowed to fetch visitor data.
        /// </summary>
        internal static string Only_user_with_Document_Manager_role_is_allowed_to_fetch_visitor_data {
            get {
                return ResourceManager.GetString("Only user with Document Manager role is allowed to fetch visitor data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Document Manager role is allowed to move the queue forward.
        /// </summary>
        internal static string Only_user_with_Document_Manager_role_is_allowed_to_move_the_queue_forward {
            get {
                return ResourceManager.GetString("Only user with Document Manager role is allowed to move the queue forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Medic Lab role is allowed to set results of tests.
        /// </summary>
        internal static string Only_user_with_Medic_Lab_role_is_allowed_to_set_results_of_tests {
            get {
                return ResourceManager.GetString("Only user with Medic Lab role is allowed to set results of tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user with Registration Manager role or Medic Tester role is allowed to fetch data of visitors.
        /// </summary>
        internal static string Only_user_with_Registration_Manager_role_or_Medic_Tester_role_is_allowed_to_fetch_data_of_visitors {
            get {
                return ResourceManager.GetString("Only user with Registration Manager role or Medic Tester role is allowed to fetch" +
                        " data of visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number must not be empty.
        /// </summary>
        internal static string Personal_number_must_not_be_empty {
            get {
                return ResourceManager.GetString("Personal number must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of the test must not be empty.
        /// </summary>
        internal static string Result_of_the_test_must_not_be_empty {
            get {
                return ResourceManager.GetString("Result of the test must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code must not be empty.
        /// </summary>
        internal static string Test_code_must_not_be_empty {
            get {
                return ResourceManager.GetString("Test code must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test id must not be empty.
        /// </summary>
        internal static string Test_id_must_not_be_empty {
            get {
                return ResourceManager.GetString("Test id must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor code must not be empty.
        /// </summary>
        internal static string Visitor_code_must_not_be_empty {
            get {
                return ResourceManager.GetString("Visitor code must not be empty", resourceCulture);
            }
        }
    }
}
