//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidMassTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_AdminController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_AdminController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidMassTesting.Resources.Controllers.AdminController", typeof(Controllers_AdminController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password.
        /// </summary>
        internal static string Invalid_user_or_password {
            get {
                return ResourceManager.GetString("Invalid user or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admin is allowed to drop database.
        /// </summary>
        internal static string Only_admin_is_allowed_to_drop_database {
            get {
                return ResourceManager.GetString("Only admin is allowed to drop database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admin is allowed to invite other users.
        /// </summary>
        internal static string Only_admin_is_allowed_to_invite_other_users {
            get {
                return ResourceManager.GetString("Only admin is allowed to invite other users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admin is allowed to manage time.
        /// </summary>
        internal static string Only_admin_is_allowed_to_manage_time {
            get {
                return ResourceManager.GetString("Only admin is allowed to manage time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admin is allowed to remove users.
        /// </summary>
        internal static string Only_admin_is_allowed_to_remove_users {
            get {
                return ResourceManager.GetString("Only admin is allowed to remove users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is protected by the configuration.
        /// </summary>
        internal static string This_user_is_protected_by_the_configuration {
            get {
                return ResourceManager.GetString("This user is protected by the configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself.
        /// </summary>
        internal static string You_cannot_remove_yourself {
            get {
                return ResourceManager.GetString("You cannot remove yourself", resourceCulture);
            }
        }
    }
}
