//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidMassTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Repository_RedisRepository_VisitorRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Repository_RedisRepository_VisitorRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidMassTesting.Resources.Repository.RedisRepository.VisitorRepository", typeof(Repository_RedisRepository_VisitorRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covid test.
        /// </summary>
        internal static string Covid_test {
            get {
                return ResourceManager.GetString("Covid test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, {1} is your registration code. Show this code at the covid sampling place {3} on {2}.
        /// </summary>
        internal static string Dear__0____1__is_your_registration_code__Show_this_code_at_the_covid_sampling_place__3__on__2_ {
            get {
                return ResourceManager.GetString("Dear {0}, {1} is your registration code. Show this code at the covid sampling pla" +
                        "ce {3} on {2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, there were some technical issues with your test. Please visit the sampling place again and repeat the test procedure. You can use the same registration as before..
        /// </summary>
        internal static string Dear__0___there_were_some_technical_issues_with_your_test__Please_visit_the_sampling_place_again_and_repeat_the_test_procedure__You_can_use_the_same_registration_as_before_ {
            get {
                return ResourceManager.GetString("Dear {0}, there were some technical issues with your test. Please visit the sampl" +
                        "ing place again and repeat the test procedure. You can use the same registration" +
                        " as before.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, we have updated your registration {1}. Time: {2}, Place: {3}.
        /// </summary>
        internal static string Dear__0___we_have_updated_your_registration__1___Time___2___Place___3_ {
            get {
                return ResourceManager.GetString("Dear {0}, we have updated your registration {1}. Time: {2}, Place: {3}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, your test is in processing. Please wait for further instructions in next sms message..
        /// </summary>
        internal static string Dear__0___your_test_is_in_processing__Please_wait_for_further_instructions_in_next_sms_message_ {
            get {
                return ResourceManager.GetString("Dear {0}, your test is in processing. Please wait for further instructions in nex" +
                        "t sms message.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, your test result has been processed. You can check the result online. Please come to take the certificate..
        /// </summary>
        internal static string Dear__0___your_test_result_has_been_processed__You_can_check_the_result_online__Please_come_to_take_the_certificate_ {
            get {
                return ResourceManager.GetString("Dear {0}, your test result has been processed. You can check the result online. P" +
                        "lease come to take the certificate.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},We have removed your personal data from the database. Thank you for taking the covid test.
        /// </summary>
        internal static string Dear__0__We_have_removed_your_personal_data_from_the_database__Thank_you_for_taking_the_covid_test {
            get {
                return ResourceManager.GetString("Dear {0},We have removed your personal data from the database. Thank you for taki" +
                        "ng the covid test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 4 digits of personal number or declared passport for foreigner at registration must not be empty.
        /// </summary>
        internal static string Last_4_digits_of_personal_number_or_declared_passport_for_foreigner_at_registration_must_not_be_empty {
            get {
                return ResourceManager.GetString("Last 4 digits of personal number or declared passport for foreigner at registrati" +
                        "on must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data may be deleted only after the test has proven negative result and person receives the certificate..
        /// </summary>
        internal static string Personal_data_may_be_deleted_only_after_the_test_has_proven_negative_result_and_person_receives_the_certificate_ {
            get {
                return ResourceManager.GetString("Personal data may be deleted only after the test has proven negative result and p" +
                        "erson receives the certificate.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test does not exists.
        /// </summary>
        internal static string Test_does_not_exists {
            get {
                return ResourceManager.GetString("Test does not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot;&gt;
        ///    &lt;title&gt;Test registration&lt;/title&gt;
        ///    &lt;style&gt;
        ///        h1 {
        ///            color: navy;
        ///            font-size: 2em;
        ///        }
        ///
        ///        th {
        ///            text-align: left;
        ///        }
        ///
        ///        body {
        ///            font-family: sans-serif;
        ///            font-size: 10px;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Registr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRegistration {
            get {
                return ResourceManager.GetString("TestRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot;&gt;
        ///    &lt;title&gt;Test result&lt;/title&gt;
        ///    &lt;style&gt;
        ///        h1 {
        ///            color: navy;
        ///            font-size: 2em;
        ///        }
        ///
        ///        th {
        ///            text-align: left;
        ///        }
        ///
        ///        body {
        ///            font-family: sans-serif;
        ///            font-size: 10px;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Výsledok test [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This 1 hour time slot has reached the capacity..
        /// </summary>
        internal static string This_1_hour_time_slot_has_reached_the_capacity_ {
            get {
                return ResourceManager.GetString("This 1 hour time slot has reached the capacity.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This 5 minute time slot has reached the capacity..
        /// </summary>
        internal static string This_5_minute_time_slot_has_reached_the_capacity_ {
            get {
                return ResourceManager.GetString("This 5 minute time slot has reached the capacity.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find visitor code from test code. Are you sure test code is correct?.
        /// </summary>
        internal static string Unable_to_find_visitor_code_from_test_code__Are_you_sure_test_code_is_correct_ {
            get {
                return ResourceManager.GetString("Unable to find visitor code from test code. Are you sure test code is correct?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown personal number.
        /// </summary>
        internal static string Unknown_personal_number {
            get {
                return ResourceManager.GetString("Unknown personal number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor with code {0} not found.
        /// </summary>
        internal static string Visitor_with_code__0__not_found {
            get {
                return ResourceManager.GetString("Visitor with code {0} not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to find chosen 5 min. slot.
        /// </summary>
        internal static string We_are_not_able_to_find_chosen_5_min__slot {
            get {
                return ResourceManager.GetString("We are not able to find chosen 5 min. slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to find chosen hour slot.
        /// </summary>
        internal static string We_are_not_able_to_find_chosen_hour_slot {
            get {
                return ResourceManager.GetString("We are not able to find chosen hour slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to find chosen testing place.
        /// </summary>
        internal static string We_are_not_able_to_find_chosen_testing_place {
            get {
                return ResourceManager.GetString("We are not able to find chosen testing place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can remove only first item from the queue.
        /// </summary>
        internal static string You_can_remove_only_first_item_from_the_queue {
            get {
                return ResourceManager.GetString("You can remove only first item from the queue", resourceCulture);
            }
        }
    }
}
