//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidMassTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Repository_RedisRepository_UserRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Repository_RedisRepository_UserRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidMassTesting.Resources.Repository.RedisRepository.UserRepository", typeof(Repository_RedisRepository_UserRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, we have registered you into mass covid testing system. Please check your email..
        /// </summary>
        internal static string Dear__0___we_have_registered_you_into_mass_covid_testing_system__Please_check_your_email_ {
            get {
                return ResourceManager.GetString("Dear {0}, we have registered you into mass covid testing system. Please check you" +
                        "r email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty.
        /// </summary>
        internal static string Email_must_not_be_empty {
            get {
                return ResourceManager.GetString("Email must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating record in the database.
        /// </summary>
        internal static string Error_creating_record_in_the_database {
            get {
                return ResourceManager.GetString("Error creating record in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash must not be empty.
        /// </summary>
        internal static string Hash_must_not_be_empty {
            get {
                return ResourceManager.GetString("Hash must not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        internal static string Invalid_old_password {
            get {
                return ResourceManager.GetString("Invalid old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid place provided.
        /// </summary>
        internal static string Invalid_place_provided {
            get {
                return ResourceManager.GetString("Invalid place provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password.
        /// </summary>
        internal static string Invalid_user_or_password {
            get {
                return ResourceManager.GetString("Invalid user or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password or attempt to login too fast after failed attempt.
        /// </summary>
        internal static string Invalid_user_or_password_or_attempt_to_login_too_fast_after_failed_attempt {
            get {
                return ResourceManager.GetString("Invalid user or password or attempt to login too fast after failed attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found by email.
        /// </summary>
        internal static string User_not_found_by_email {
            get {
                return ResourceManager.GetString("User not found by email", resourceCulture);
            }
        }
    }
}
